apiVersion: v1
kind: Service
metadata:
  name: workspace-api
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  workspace_mapping
      prefix: /api/workspace/
      service: workspace-api:8080
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: http
  selector:
    app: workspace-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-api
spec:
  selector:
    matchLabels:
      app: workspace-api
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: workspace-api
        version: '1'
    spec:
      containers:
      - name: workspace-api
        image: jasonblanchard/jawn-workspace-api:1
        env:
          - name: 'PORT'
            value: '8080'
          - name: 'MONGO_HOST'
            value: 'workspace-mongo'
          - name: 'DB_NAME'
            value: 'jawn'
          - name: 'LOG_LEVEL'
            value: 'DEBUG'
          - name: 'JWT_SECRET'
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: jwtSecret
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
             path: /health
             port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
